// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type EntryFromType string

const (
	EntryFromTypeTM EntryFromType = "TM"
	EntryFromTypeIT EntryFromType = "IT"
)

func (e *EntryFromType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EntryFromType(s)
	case string:
		*e = EntryFromType(s)
	default:
		return fmt.Errorf("unsupported scan type for EntryFromType: %T", src)
	}
	return nil
}

type NullEntryFromType struct {
	EntryFromType EntryFromType `json:"entry_from_type"`
	Valid         bool          `json:"valid"` // Valid is true if EntryFromType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEntryFromType) Scan(value interface{}) error {
	if value == nil {
		ns.EntryFromType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EntryFromType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEntryFromType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EntryFromType), nil
}

type InvestmentStatus string

const (
	InvestmentStatusInactive InvestmentStatus = "inactive"
	InvestmentStatusActive   InvestmentStatus = "active"
	InvestmentStatusBuyout   InvestmentStatus = "buyout"
)

func (e *InvestmentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InvestmentStatus(s)
	case string:
		*e = InvestmentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for InvestmentStatus: %T", src)
	}
	return nil
}

type NullInvestmentStatus struct {
	InvestmentStatus InvestmentStatus `json:"investment_status"`
	Valid            bool             `json:"valid"` // Valid is true if InvestmentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInvestmentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.InvestmentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InvestmentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInvestmentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InvestmentStatus), nil
}

type Account struct {
	ID          int64              `json:"id"`
	ChannelName string             `json:"channel_name"`
	Owner       string             `json:"owner"`
	Balance     int64              `json:"balance"`
	Currency    string             `json:"currency"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type AccountEntry struct {
	ID        int64 `json:"id"`
	AccountID int64 `json:"account_id"`
	// can be possitive or negative
	Amount    int64              `json:"amount"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	FromType  EntryFromType      `json:"from_type"`
}

type Investment struct {
	ID              int64            `json:"id"`
	AccountID       int64            `json:"account_id"`
	StockCode       string           `json:"stock_code"`
	CompanyName     pgtype.Text      `json:"company_name"`
	TotalBuyAmount  int32            `json:"total_buy_amount"`
	TotalMoneyBuy   int64            `json:"total_money_buy"`
	CapitalCost     int64            `json:"capital_cost"`
	MarketPrice     int64            `json:"market_price"`
	TotalSellAmount int32            `json:"total_sell_amount"`
	TotalMoneySell  int64            `json:"total_money_sell"`
	CurrentVolume   int32            `json:"current_volume"`
	Description     pgtype.Text      `json:"description"`
	Status          InvestmentStatus `json:"status"`
}

type Transaction struct {
	ID           int64 `json:"id"`
	InvestmentID int64 `json:"investment_id"`
	CapitalCost  int64 `json:"capital_cost"`
	Price        int64 `json:"price"`
	// must be possitive
	Amount    int32              `json:"amount"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Type      string             `json:"type"`
	Fee       int64              `json:"fee"`
}
