// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateInvestment(ctx context.Context, arg CreateInvestmentParams) (Investment, error)
	ListAccounts(ctx context.Context) ([]Account, error)
}

var _ Querier = (*Queries)(nil)
