ALTER TABLE investments
ALTER COLUMN buy_value SET DEFAULT NULL;

ALTER TABLE investments
ALTER COLUMN capital_cost SET DEFAULT NULL;

ALTER TABLE investments
ALTER COLUMN market_price SET DEFAULT NULL;

ALTER TABLE investments
ALTER COLUMN fee SET DEFAULT NULL;

ALTER TABLE investments
ALTER COLUMN tax SET DEFAULT NULL;