ALTER TABLE accounts 
ALTER COLUMN balance SET DATA TYPE NUMERIC(10,3);

ALTER TABLE account_entries 
ALTER COLUMN amount SET DATA TYPE NUMERIC(10,3);

ALTER TABLE investments
ALTER COLUMN total_money_buy SET DATA TYPE NUMERIC(10,3),
ALTER COLUMN capital_cost SET DATA TYPE NUMERIC(10,3),
ALTER COLUMN market_price SET DATA TYPE NUMERIC(10,3),
ALTER COLUMN total_money_sell SET DATA TYPE NUMERIC(10,3);
 
ALTER TABLE transactions 
ALTER COLUMN capital_cost SET DATA TYPE NUMERIC(10,3),
ALTER COLUMN price SET DATA TYPE NUMERIC(10,3),
ALTER COLUMN fee SET DATA TYPE NUMERIC(10,3);