ALTER TABLE accounts
ALTER COLUMN balance SET DATA TYPE BIGINT;

ALTER TABLE account_entries
ALTER COLUMN amount SET DATA TYPE BIGINT;

ALTER TABLE investments
ALTER COLUMN total_money_buy SET DATA TYPE BIGINT,
ALTER COLUMN capital_cost SET DATA TYPE BIGINT,
ALTER COLUMN market_price SET DATA TYPE BIGINT,
ALTER COLUMN total_money_sell SET DATA TYPE BIGINT;

ALTER TABLE transactions 
ALTER COLUMN capital_cost SET DATA TYPE BIGINT,
ALTER COLUMN price SET DATA TYPE BIGINT,
ALTER COLUMN fee SET DATA TYPE BIGINT;