// Code generated by MockGen. DO NOT EDIT.
// Source: stt/services/interfaces (interfaces: IAccountService,IInvestmentService,IUserService)

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	reflect "reflect"
	db "stt/database/postgres/sqlc"
	dtos "stt/services/dtos"

	gomock "github.com/golang/mock/gomock"
)

// MockIAccountService is a mock of IAccountService interface.
type MockIAccountService struct {
	ctrl     *gomock.Controller
	recorder *MockIAccountServiceMockRecorder
}

// MockIAccountServiceMockRecorder is the mock recorder for MockIAccountService.
type MockIAccountServiceMockRecorder struct {
	mock *MockIAccountService
}

// NewMockIAccountService creates a new mock instance.
func NewMockIAccountService(ctrl *gomock.Controller) *MockIAccountService {
	mock := &MockIAccountService{ctrl: ctrl}
	mock.recorder = &MockIAccountServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAccountService) EXPECT() *MockIAccountServiceMockRecorder {
	return m.recorder
}

// CreateNew mocks base method.
func (m *MockIAccountService) CreateNew(arg0 context.Context, arg1 db.CreateAccountParams) (db.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNew", arg0, arg1)
	ret0, _ := ret[0].(db.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNew indicates an expected call of CreateNew.
func (mr *MockIAccountServiceMockRecorder) CreateNew(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNew", reflect.TypeOf((*MockIAccountService)(nil).CreateNew), arg0, arg1)
}

// Delete mocks base method.
func (m *MockIAccountService) Delete(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIAccountServiceMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIAccountService)(nil).Delete), arg0, arg1)
}

// GetAccountInfoByIds mocks base method.
func (m *MockIAccountService) GetAccountInfoByIds(arg0 context.Context, arg1 []int64) ([]db.GetAccountInfoByIdsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountInfoByIds", arg0, arg1)
	ret0, _ := ret[0].([]db.GetAccountInfoByIdsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountInfoByIds indicates an expected call of GetAccountInfoByIds.
func (mr *MockIAccountServiceMockRecorder) GetAccountInfoByIds(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountInfoByIds", reflect.TypeOf((*MockIAccountService)(nil).GetAccountInfoByIds), arg0, arg1)
}

// GetAllByOwner mocks base method.
func (m *MockIAccountService) GetAllByOwner(arg0 context.Context, arg1 string) ([]db.GetAccountPagingRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllByOwner", arg0, arg1)
	ret0, _ := ret[0].([]db.GetAccountPagingRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllByOwner indicates an expected call of GetAllByOwner.
func (mr *MockIAccountServiceMockRecorder) GetAllByOwner(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllByOwner", reflect.TypeOf((*MockIAccountService)(nil).GetAllByOwner), arg0, arg1)
}

// GetById mocks base method.
func (m *MockIAccountService) GetById(arg0 context.Context, arg1 int64) (db.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", arg0, arg1)
	ret0, _ := ret[0].(db.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockIAccountServiceMockRecorder) GetById(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockIAccountService)(nil).GetById), arg0, arg1)
}

// ListAllByOwner mocks base method.
func (m *MockIAccountService) ListAllByOwner(arg0 context.Context, arg1 string) ([]db.ListAllAccountRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllByOwner", arg0, arg1)
	ret0, _ := ret[0].([]db.ListAllAccountRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllByOwner indicates an expected call of ListAllByOwner.
func (mr *MockIAccountServiceMockRecorder) ListAllByOwner(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllByOwner", reflect.TypeOf((*MockIAccountService)(nil).ListAllByOwner), arg0, arg1)
}

// TransferMoney mocks base method.
func (m *MockIAccountService) TransferMoney(arg0 context.Context, arg1 dtos.TransferMoneyTxParam) (dtos.TransferMoneyTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransferMoney", arg0, arg1)
	ret0, _ := ret[0].(dtos.TransferMoneyTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransferMoney indicates an expected call of TransferMoney.
func (mr *MockIAccountServiceMockRecorder) TransferMoney(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransferMoney", reflect.TypeOf((*MockIAccountService)(nil).TransferMoney), arg0, arg1)
}

// UpdateBalance mocks base method.
func (m *MockIAccountService) UpdateBalance(arg0 context.Context, arg1 db.AddAccountBalanceParams) (db.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBalance", arg0, arg1)
	ret0, _ := ret[0].(db.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBalance indicates an expected call of UpdateBalance.
func (mr *MockIAccountServiceMockRecorder) UpdateBalance(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBalance", reflect.TypeOf((*MockIAccountService)(nil).UpdateBalance), arg0, arg1)
}

// MockIInvestmentService is a mock of IInvestmentService interface.
type MockIInvestmentService struct {
	ctrl     *gomock.Controller
	recorder *MockIInvestmentServiceMockRecorder
}

// MockIInvestmentServiceMockRecorder is the mock recorder for MockIInvestmentService.
type MockIInvestmentServiceMockRecorder struct {
	mock *MockIInvestmentService
}

// NewMockIInvestmentService creates a new mock instance.
func NewMockIInvestmentService(ctrl *gomock.Controller) *MockIInvestmentService {
	mock := &MockIInvestmentService{ctrl: ctrl}
	mock.recorder = &MockIInvestmentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIInvestmentService) EXPECT() *MockIInvestmentServiceMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockIInvestmentService) Count(arg0 context.Context, arg1 db.CountInvestmentParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockIInvestmentServiceMockRecorder) Count(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockIInvestmentService)(nil).Count), arg0, arg1)
}

// Create mocks base method.
func (m *MockIInvestmentService) Create(arg0 context.Context, arg1 db.CreateInvestmentParams) (db.Investment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(db.Investment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIInvestmentServiceMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIInvestmentService)(nil).Create), arg0, arg1)
}

// GetById mocks base method.
func (m *MockIInvestmentService) GetById(arg0 context.Context, arg1 int64) (db.Investment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", arg0, arg1)
	ret0, _ := ret[0].(db.Investment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockIInvestmentServiceMockRecorder) GetById(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockIInvestmentService)(nil).GetById), arg0, arg1)
}

// GetByTicker mocks base method.
func (m *MockIInvestmentService) GetByTicker(arg0 context.Context, arg1 string) (db.Investment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTicker", arg0, arg1)
	ret0, _ := ret[0].(db.Investment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTicker indicates an expected call of GetByTicker.
func (mr *MockIInvestmentServiceMockRecorder) GetByTicker(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTicker", reflect.TypeOf((*MockIInvestmentService)(nil).GetByTicker), arg0, arg1)
}

// SearchPaging mocks base method.
func (m *MockIInvestmentService) SearchPaging(arg0 context.Context, arg1 db.SearchInvestmentPagingParams) ([]db.SearchInvestmentPagingRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchPaging", arg0, arg1)
	ret0, _ := ret[0].([]db.SearchInvestmentPagingRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchPaging indicates an expected call of SearchPaging.
func (mr *MockIInvestmentServiceMockRecorder) SearchPaging(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchPaging", reflect.TypeOf((*MockIInvestmentService)(nil).SearchPaging), arg0, arg1)
}

// MockIUserService is a mock of IUserService interface.
type MockIUserService struct {
	ctrl     *gomock.Controller
	recorder *MockIUserServiceMockRecorder
}

// MockIUserServiceMockRecorder is the mock recorder for MockIUserService.
type MockIUserServiceMockRecorder struct {
	mock *MockIUserService
}

// NewMockIUserService creates a new mock instance.
func NewMockIUserService(ctrl *gomock.Controller) *MockIUserService {
	mock := &MockIUserService{ctrl: ctrl}
	mock.recorder = &MockIUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUserService) EXPECT() *MockIUserServiceMockRecorder {
	return m.recorder
}

// CreateNew mocks base method.
func (m *MockIUserService) CreateNew(arg0 context.Context, arg1 db.CreateUserParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNew", arg0, arg1)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNew indicates an expected call of CreateNew.
func (mr *MockIUserServiceMockRecorder) CreateNew(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNew", reflect.TypeOf((*MockIUserService)(nil).CreateNew), arg0, arg1)
}

// GetByUserName mocks base method.
func (m *MockIUserService) GetByUserName(arg0 context.Context, arg1 string) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserName", arg0, arg1)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserName indicates an expected call of GetByUserName.
func (mr *MockIUserServiceMockRecorder) GetByUserName(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserName", reflect.TypeOf((*MockIUserService)(nil).GetByUserName), arg0, arg1)
}
